name: Plop
favicon: null
layout_spectrum: 0.35049191885627806
typography_spectrum: 0.37286199047230184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15855664410628378
  lightness: 0.36262092273682356
  saturation: 0.014250917127355933
  rhythmicContrast: 0.24377284781076014
purpose: []
